routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {

    if (auth()->check()) {

        return redirect()->route('admin.dashboard.index');
    } else {
        return view('auth.login');
    }

})->name('index');


Auth::routes(['verify' => true]);
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');

//    \Illuminate\Support\Facades\Artisan::call('passport:install');
//    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


//Forget Password
Route::get('/user/verify/{token}', 'Auth\LoginController@activation');


Route::post('otp', 'Auth\ForgotPasswordController@otp')->name('otp.send');
Route::post('verify/otp', 'Auth\ForgotPasswordController@verifyOTP')->name('verify.otp');
Route::post('forgot-password-request', 'Auth\ForgotPasswordController@ForgotPasswordRequest')->name('otp.password.reset');

Route::get('/home', 'HomeController@index')->name('home');

//Landing Page Routes

Route::get('about-us', 'Frontend\AboutUsController@index')->name('aboutus.detail');
Route::get('how-it-works', 'Frontend\AboutUsController@howItWorks')->name('how.its.works.detail');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/meta-tags', 'Backend\MetaTagController', [
            'only' => ['index', 'create', 'store', 'edit', 'update']
        ]);
        Route::resource('/cities', 'Backend\CityController');
        Route::resource('/states', 'Backend\StateController');

        //Blogs Routes Start
        Route::resource('/blogs', 'Backend\BlogController');
        Route::post('add/blog/comments', 'Backend\BlogController@addComment')->name('add.blogs.comments');
        Route::get('view/comments/{blog_id}', 'Backend\BlogController@viewComments')->name('view.blogs.comments');
        Route::get('update/blog/comment/status', 'Backend\BlogController@updateStatus')->name('update.blog.comment.status');
        Route::delete('blog/comments/delete/{blog_id}', 'Backend\BlogController@deleteComment')->name('blogs.comment.destroy');
        //Blogs Routes End

        //Events Routes Start
        Route::resource('/events', 'Backend\EventController');
        Route::get('event/gallery/add/{event_id}', 'Backend\EventController@addEventGallery')->name('event.gallery.add');
        Route::get('event/gallery/view/{event_id}', 'Backend\EventController@viewEventGallery')->name('event.gallery.view');
        Route::post('event/gallery/store', 'Backend\EventController@storeEventGallery')->name('event.gallery.store');
        Route::post('event/gallery/delete', 'Backend\EventController@destroyEventGallery')->name('event.gallery.destroy');
        Route::delete('event/gallery/single/delete/{event_id}', 'Backend\EventController@singleDestroyEventGallery')->name('event.gallery.single.destroy');
        Route::resource('/event-galleries', 'Backend\EventGalleryController');
        //Events Routes End


        //Library Dua Routes Start
        Route::resource('/dua-categories', 'Backend\DuaCategoryController');
        Route::resource('/dua-sub-categories', 'Backend\DuaSubCategoryController');
        //Library Dua Routes End


        //Momin TV Routes Start
        Route::resource('/momin-tv', 'Backend\MominTvCategoryController');
        Route::resource('/videos', 'Backend\MominTvVideoController');
        //Momin TV Routes End

        Route::post('/states/import/file', 'Backend\StateController@importFile')->name('states.import.excel');
        Route::resource('/users', 'Backend\UserController');
        Route::post('/users/location', 'Backend\UserController@updateLocation')->name('user.location');


        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/aboutus', 'Backend\AboutUsController', [
            'only' => ['index', 'store']
        ]);
        Route::resource('/banner', 'Backend\BannerController', [
            'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
        ]);

        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);

        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');


        //Aal-e-Muhammad
        Route::resource('aal-e-muhammad', 'Backend\AaleMuhammadController');

        //Calender Events
        Route::resource('calendar-events', 'Backend\CalenderEventController');

        //Hadees
        Route::resource('hadees', 'Backend\HadeesController');


    });

    Route::get('/sendsms/{phone}/{message}', 'Backend\SendReferralCodeController@sendCodeWithPhone');
});

Route::get('privacy-policy', function () {
    $privacyPolicy = \App\Models\PrivacyPolicy::first();
    return view('frontend.pages.privacy-policy', compact('privacyPolicy'));
})->name('privacy.policy');


//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {

    Route::get('state-cities', 'Backend\AjaxController@stateCities')->name('stateCities');
});
Route::resource('/contacts', 'Backend\ContactUsController', [
    'only' => ['create', 'store']
]);
Route::get('/contacts', 'Backend\ContactUsController@create')->name('contacts.create');
Route::post('/contacts/store', 'Backend\ContactUsController@store')->name('contacts.store');

app/Models/AaleMuhammad.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AaleMuhammad extends Model
{
    protected $table = "aale_muhammads";
    protected $guarded = [];
}

app/Http/Controllers/Backend/AaleMuhammadController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

use App\Models\AaleMuhammad;
use Illuminate\Http\Request;

class AaleMuhammadController extends Controller
{
    public function index()
    {
        $getData = AaleMuhammad::all();
        return view('backend.aal-e-muhammad.index', compact('getData'));
    }

    public function create()
    {
        return view('backend.aal-e-muhammad.create');
    }

    public function store(Request $request)
    {

        $this->validate($request, [
            'title'             => 'required',
            'description'       => 'required',

        ], [
            'title.required'         => 'Title is required.',
            'description.required'   => 'Description is required.',
        ]);


        AaleMuhammad::create([
            'title'         => $request->title,
            'description'   => $request->description,
        ]);

        return redirect()->route('admin.aal-e-muhammad.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Record created successfully.'
            ]);
    }

    public function edit($id)
    {
        $data = AaleMuhammad::find($id);
        return view('backend.aal-e-muhammad.edit', compact('data'));


    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title'             => 'required',
            'description'       => 'required',

        ], [
            'title.required'         => 'Title is required.',
            'description.required'   => 'Description is required.',

        ]);

        $data = AaleMuhammad::find($id);
        $data->update([
            'title'         => $request->title,
            'description'   => $request->description,
        ]);

        return redirect()->route('admin.aal-e-muhammad.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Record updated successfully.'
            ]);
    }

    public function destroy($id)
    {
        $data = AaleMuhammad::findOrFail($id);
        $data->delete();

        return redirect()->route('admin.aal-e-muhammad.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Record has been deleted'
            ]);
    }
}

app/Http/Controllers/Backend/AboutUsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Aboutus;
use Illuminate\Http\Request;

class AboutUsController extends Controller
{
    public function index()
    {
        $aboutus = Aboutus::first();
        return view('backend.aboutus.create', compact('aboutus'));
    }

    public function store(Request $request)
    {


        $this->validate($request, [
            'summary' => 'required',
            'description' => 'required',
        ], [
            'summary.required' => 'Summary is required.',
            'description.required' => 'Description is required.'
        ]);
        $aboutus = Aboutus::findOrFail(1);

        $aboutus->update([
            'summary' => $request->summary,
            'description' => $request->description
        ]);
        return back()->with([
            'flash_status' => 'success',
            'flash_message' => 'About us description updated successfully.'
        ]);
    }
}

app/Http/Controllers/Backend/AjaxController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

use App\Models\City;
use App\Traits\GeneralHelperTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;



class AjaxController extends Controller
{
    use GeneralHelperTrait;

    public function example(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
        ], [

        ]);

        if (!$validator->fails()) {


            $response['status'] = 'success';
            $response['data'] = [

            ];
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;
    }

    public function stateCities(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'state_id' => 'required|exists:states,id'
        ], [
            'state_id.required' => "State is Required.",
            'state_id.exists' => "Invalid State Selected."
        ]);

        if (!$validator->fails()) {
            $cities = City::where('state_id', $request->state_id)->orderBy('name', 'asc')->get();

            $response['status'] = 'success';
            $response['data'] = [
                'cities' => $cities,
            ];
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;
    }



}

app/Http/Controllers/Backend/CalenderEventController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;

use App\Models\CalenderEvent;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CalenderEventController extends Controller
{
    public function __construct()
    {

        $this->middleware('role:admin');
    }

    public function index()
    {
        $events = CalenderEvent::orderBy('id', 'DESC')->get();
        return view('backend.calendar-events.index', compact('events'));
    }

    public function create()
    {
        return view('backend.calendar-events.create');
    }

    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required',
            'english_date' => 'required',
            'islamic_date' => 'required',

        ], [
            'title.required' => 'Title is required.',
            'english_date.required' => 'English Date is required.',
            'islamic_date.required' => 'Islamic Date is required.',
        ]);
        $calenderEvents = CalenderEvent::create([
            'title' => $request->title,
            'english_date' => date('Y-m-d', strtotime($request->english_date)),
            'islamic_date' => $request->islamic_date,
        ]);

        return redirect()->route('admin.calendar-events.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Calender Event created successfully.'
            ]);
    }

    public function edit($id)
    {
        $event = CalenderEvent::find($id);
        return view('backend.calendar-events.edit', compact('event'));


    }

    public function update(Request $request, $id)
    {

        $this->validate($request, [
            'title' => 'required',
            'english_date' => 'required',
            'islamic_date' => 'required',

        ], [
            'title.required' => 'Title is required.',
            'english_date.required' => 'English Date is required.',
            'islamic_date.required' => 'Islamic Date is required.',
        ]);

        $calenderEvents = CalenderEvent::find($id);

        $calenderEvents->update([
            'title' => $request->title,
            'english_date' => date('Y-m-d', strtotime($request->english_date)),
            'islamic_date' => $request->islamic_date,
        ]);

        return redirect()->route('admin.calendar-events.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Calender Event updated successfully.'
            ]);
    }

    public function destroy($id)
    {
        $calenderEvents = CalenderEvent::findOrFail($id);
        $calenderEvents->delete();

        return redirect()->route('admin.calendar-events.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Calender Event has been deleted'
            ]);
    }


}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $users_count = User::all()->count();
        $staff_users = User::where('user_type', 'realtor')->get()->toArray();

        return view('backend.dashboard.index', compact('users_count', 'staff_users'));
    }
}

app/Http/Controllers/Backend/EventGalleryController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class EventGalleryController extends Controller
{
    //
}

app/Http/Controllers/Backend/NotificationController.php
<?php


namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class NotificationController extends Controller
{
    //
}

resources/views/backend/aal-e-muhammad/create.blade.php
@extends('layouts.master')
@section('title','Aal-e-Muhammad')
@push('css')
    <style>

        .m-portlet textarea {
            height: 100% !important;
        }
    </style>
@endpush
@section('content')


    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Add
                        </h3>
                    </div>
                </div>
            </div>

            <div class="m-portlet__body">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form class="m-form" method="post" action="{{ route('admin.aal-e-muhammad.store') }}" id="create"
                              enctype="multipart/form-data" role="form">
                            @csrf
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">

                                    <div class="form-group row">
                                        <div class="col-md-12">
                                            <label for="title"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Title') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input id="title" type="text"
                                                   class="form-control @error('title') is-invalid @enderror"
                                                   name="title" value="{{ old('title') }}"
                                                   autocomplete="title" autofocus>

                                            @error('title')
                                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-12">
                                            <label for="description"><strong>Description </strong><span class="mandatorySign">*</span></label>
                                            <textarea name="description" id="description" rows="10"
                                                      cols="80"
                                                      style="
                                                      margin-top: 0px;
                                                      margin-bottom: 0px;
                                                      height: 147px !important;"
                                            ></textarea>

                                            @error('description')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit text-md-right">
                                <div class="m-form__actions m-form__actions">
                                    <a href="{{ route('admin.aal-e-muhammad.index') }}" class="btn btn-info">Back</a>
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('SAVE') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')

    <script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('description');
    </script>
@endpush

resources/views/backend/aal-e-muhammad/edit.blade.php
@extends('layouts.master')
@section('title','Aal-e-Muhammad')
@push('css')
    <style>
        .modal .modal-content .modal-header {

            background: #f1743b !important;
        }

        .modal .modal-content .modal-header .modal-title {
            color: #fff !important;
        }


        .button-right {
            float: right;
            margin-top: 12px;
        }
       .m-portlet textarea{
            height: 100% !important;
        }
    </style>
@endpush
@section('content')


    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Edit
                        </h3>
                    </div>
                </div>

            </div>


            <div class="m-portlet__body">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form class="m-form" method="post" action="{{ route('admin.aal-e-muhammad.update',$data->id) }}"
                              id="create"
                              enctype="multipart/form-data" role="form">
                            @method('patch')
                            @csrf
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">
                                    <div class="form-group row">
                                        <div class="col-md-12">
                                            <label for="title"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Title') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input id="title" type="text"
                                                   class="form-control @error('title') is-invalid @enderror"
                                                   name="title" value="{{ old('title',$data->title) }}"
                                                   autocomplete="title" autofocus>

                                            @error('title')
                                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-12">
                                            <label for="description"><strong>Description </strong><span class="mandatorySign">*</span></label>
                                            <textarea name="description" id="description"
                                                      rows="10"
                                                      cols="80"
                                                      style="
                                                      margin-top: 0px;
                                                      margin-bottom: 0px;
                                                      height: 147px !important;"
                                            >{{ old('description',$data->description) }}</textarea>

                                            @error('description')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                    </div>


                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit text-md-right">
                                <div class="m-form__actions m-form__actions">
                                    <a href="{{ route('admin.aal-e-muhammad.index') }}" class="btn btn-info">Back</a>
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('SAVE') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
    </div>
@endsection
@push('models')


@endpush

@push('js')


    <script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('description');
    </script>
@endpush

resources/views/backend/aal-e-muhammad/index.blade.php
@extends('layouts.master')
@section('title','Aal-e-Muhammad')
@push('css')

@endpush
@section('content')

    <div class="m-content">
        <!--Begin::Section-->
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Aal-e-Muhammad
                        </h3>
                    </div>
                </div>

                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{ route('admin.aal-e-muhammad.create') }}"
                               class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Add </span>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="m-portlet__body">
                <input type="hidden">
                <div class="responsiveTable">
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                    <thead>
                    <tr>

                        <th>Sr No.</th>
                        <th>Title</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!empty($getData))
                        @foreach($getData as $data)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{ucfirst($data->title)}}</td>
                                <td  class="d-flex">

                                    <a href="{{route('admin.aal-e-muhammad.edit',$data->id)}}"
                                       class="btn btn-sm btn-info pull-left ">Edit</a>
                                    <form method="post" action="{{ route('admin.aal-e-muhammad.destroy', $data->id) }}"
                                          id="delete_{{ $data->id }}">
                                        @csrf
                                        @method('DELETE')
                                        <a class="btn btn-sm btn-danger m-left"
                                           href="javascript:void(0)"
                                           onclick="if(confirmDelete()){ document.getElementById('delete_<?=$data->id?>').submit(); }">
                                            Delete
                                        </a>
                                    </form>
                                </td>
                            </tr>

                        @endforeach
                    @endif
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $("#m_table_1").dataTable({
            "ordering": false,
            "order": [[0, "asc"]],
            "columnDefs": [
                {orderable: false, targets: [2]}
            ],
        });


    </script>
@endpush