routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {

    if (auth()->check()) {

        return redirect()->route('admin.dashboard.index');
    } else {
        return view('auth.login');
    }

})->name('index');


Auth::routes(['verify' => true]);
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');

//    \Illuminate\Support\Facades\Artisan::call('passport:install');
//    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


//Forget Password
Route::get('/user/verify/{token}', 'Auth\LoginController@activation');


Route::post('otp', 'Auth\ForgotPasswordController@otp')->name('otp.send');
Route::post('verify/otp', 'Auth\ForgotPasswordController@verifyOTP')->name('verify.otp');
Route::post('forgot-password-request', 'Auth\ForgotPasswordController@ForgotPasswordRequest')->name('otp.password.reset');

Route::get('/home', 'HomeController@index')->name('home');

//Landing Page Routes

Route::get('about-us', 'Frontend\AboutUsController@index')->name('aboutus.detail');
Route::get('how-it-works', 'Frontend\AboutUsController@howItWorks')->name('how.its.works.detail');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/meta-tags', 'Backend\MetaTagController', [
            'only' => ['index', 'create', 'store', 'edit', 'update']
        ]);
        Route::resource('/cities', 'Backend\CityController');
        Route::resource('/states', 'Backend\StateController');

        //Blogs Routes Start
        Route::resource('/blogs', 'Backend\BlogController');
        Route::post('add/blog/comments', 'Backend\BlogController@addComment')->name('add.blogs.comments');
        Route::get('view/comments/{blog_id}', 'Backend\BlogController@viewComments')->name('view.blogs.comments');
        Route::get('update/blog/comment/status', 'Backend\BlogController@updateStatus')->name('update.blog.comment.status');
        Route::delete('blog/comments/delete/{blog_id}', 'Backend\BlogController@deleteComment')->name('blogs.comment.destroy');
        //Blogs Routes End

        //Events Routes Start
        Route::resource('/events', 'Backend\EventController');
        Route::get('event/gallery/add/{event_id}', 'Backend\EventController@addEventGallery')->name('event.gallery.add');
        Route::get('event/gallery/view/{event_id}', 'Backend\EventController@viewEventGallery')->name('event.gallery.view');
        Route::post('event/gallery/store', 'Backend\EventController@storeEventGallery')->name('event.gallery.store');
        Route::post('event/gallery/delete', 'Backend\EventController@destroyEventGallery')->name('event.gallery.destroy');
        Route::delete('event/gallery/single/delete/{event_id}', 'Backend\EventController@singleDestroyEventGallery')->name('event.gallery.single.destroy');
        Route::resource('/event-galleries', 'Backend\EventGalleryController');
        //Events Routes End


        //Library Dua Routes Start
        Route::resource('/dua-categories', 'Backend\DuaCategoryController');
        Route::resource('/dua-sub-categories', 'Backend\DuaSubCategoryController');
        //Library Dua Routes End


        //Momin TV Routes Start
        Route::resource('/momin-tv', 'Backend\MominTvCategoryController');
        Route::resource('/videos', 'Backend\MominTvVideoController');
        //Momin TV Routes End

        Route::post('/states/import/file', 'Backend\StateController@importFile')->name('states.import.excel');
        Route::resource('/users', 'Backend\UserController');
        Route::post('/users/location', 'Backend\UserController@updateLocation')->name('user.location');


        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/aboutus', 'Backend\AboutUsController', [
            'only' => ['index', 'store']
        ]);
        Route::resource('/banner', 'Backend\BannerController', [
            'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
        ]);

        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);

        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');


        //Aal-e-Muhammad
        Route::resource('aal-e-muhammad', 'Backend\AaleMuhammadController');

        //Calender Events
        Route::resource('calendar-events', 'Backend\CalenderEventController');

        //Hadees
        Route::resource('hadees', 'Backend\HadeesController');


    });

    Route::get('/sendsms/{phone}/{message}', 'Backend\SendReferralCodeController@sendCodeWithPhone');
});

Route::get('privacy-policy', function () {
    $privacyPolicy = \App\Models\PrivacyPolicy::first();
    return view('frontend.pages.privacy-policy', compact('privacyPolicy'));
})->name('privacy.policy');


//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {

    Route::get('state-cities', 'Backend\AjaxController@stateCities')->name('stateCities');
});
Route::resource('/contacts', 'Backend\ContactUsController', [
    'only' => ['create', 'store']
]);
Route::get('/contacts', 'Backend\ContactUsController@create')->name('contacts.create');
Route::post('/contacts/store', 'Backend\ContactUsController@store')->name('contacts.store');

resources/views/backend/dua/subcategory/create.blade.php
@extends('layouts.master')
@section('title','Duas Chapter')
@push('css')
    <style>

        .select2-container {
            width: 100% !important;
        }
    </style>
@endpush
@section('content')


    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Add {{ __('Chapter') }}
                        </h3>
                    </div>
                </div>
            </div>

            <div class="m-portlet__body">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form class="m-form" method="post" action="{{ route('admin.dua-sub-categories.store') }}"
                              id="create"
                              enctype="multipart/form-data" role="form">
                            @csrf
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">

                                    <div class="form-group row">


                                        <div class="col-md-6">
                                            <label for="title"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Title') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input id="title" type="text"
                                                   class="form-control @error('title') is-invalid @enderror"
                                                   name="title" value="{{ old('title') }}"
                                                   autocomplete="title" autofocus>

                                            @error('title')
                                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                            @enderror
                                        </div>

                                        <div class="col-md-6">
                                            <label for="category_id"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Dua') }} <span
                                                    class="mandatorySign">*</span></label>

                                            <select id="category_id"
                                                    class="form-control categories @error('category_id') is-invalid @enderror"
                                                    name="category_id" autocomplete="category_id">
                                                <option value="">Select Category</option>
                                                @if(!empty($categories))
                                                    @foreach($categories as $category)
                                                        <option
                                                            value="{{$category->id}}">{{ucfirst($category->title)}}</option>
                                                    @endforeach
                                                @endif
                                            </select>

                                            @error('category_id')
                                            <span class="invalid-feedback" role="alert">
                                              <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row">

                                        <div class="col-md-4">
                                            <label for="description_en"
                                                   class="col-md-6 col-form-label text-md-left">{{ __('English Description') }}
                                                <span class="mandatorySign">*</span></label>

                                            <textarea id="description_en"
                                                      class="form-control @error('description_en') is-invalid @enderror"
                                                      name="description_en"
                                                      autocomplete="description_en">{{ old('description_en') }}</textarea>

                                            @error('description_en')
                                            <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-4">
                                            <label for="description_ar"
                                                   class="col-md-6 col-form-label text-md-left">{{ __('Arabic Description') }}
                                                <span class="mandatorySign">*</span></label>

                                            <textarea id="description_ar"
                                                      class="form-control @error('description_ar') is-invalid @enderror"
                                                      name="description_ar"
                                                      autocomplete="description_ar">{{ old('description_ar') }}</textarea>

                                            @error('description_ar')
                                            <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-4">
                                            <label for="description_ur"
                                                   class="col-md-6 col-form-label text-md-left">{{ __('Urdu Description') }}
                                                <span class="mandatorySign">*</span></label>

                                            <textarea id="description_ur"
                                                      class="form-control @error('description_ur') is-invalid @enderror"
                                                      name="description_ur"
                                                      autocomplete="description_ur">{{ old('description_ur') }}</textarea>

                                            @error('description_ur')
                                            <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row">


                                        <div class="col-md-4">
                                            <label for="audio_en"
                                                   class="col-md-6 col-form-label text-md-left">{{ __('English Audio Link') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input id="audio_en" type="text"
                                                   class="form-control @error('audio_en') is-invalid @enderror"
                                                   name="audio_en" value="{{ old('audio_en') }}"
                                                   autocomplete="audio_en" autofocus>

                                            @error('audio_en')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-4">
                                            <label for="audio_ar"
                                                   class="col-md-6 col-form-label text-md-left">{{ __('Arabic Audio Link') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input id="audio_ar" type="text"
                                                   class="form-control @error('audio_ar') is-invalid @enderror"
                                                   name="audio_ar" value="{{ old('audio_ar') }}"
                                                   autocomplete="audio_ar" autofocus>

                                            @error('audio_ar')
                                            <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-4">
                                            <label for="audio_ur"
                                                   class="col-md-6 col-form-label text-md-left">{{ __('Urdu Audio Link') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input id="audio_ur" type="text"
                                                   class="form-control @error('audio_ur') is-invalid @enderror"
                                                   name="audio_ur" value="{{ old('audio_ur') }}"
                                                   autocomplete="audio_ur" autofocus>

                                            @error('audio_ur')
                                            <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>

                                    </div>


                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit text-md-right">
                                <div class="m-form__actions m-form__actions">
                                    <a href="{{ route('admin.dua-sub-categories.index') }}" class="btn btn-info">Back</a>
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('SAVE') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $('.categories').select2();
    </script>
@endpush

resources/views/backend/dua/subcategory/index.blade.php
@extends('layouts.master')
@section('title','Duas')
@section('content')

    <div class="m-content">
        <!--Begin::Section-->
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Dua Chapters
                        </h3>
                    </div>
                </div>

                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{ route('admin.dua-sub-categories.create') }}"
                               class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Add Dua Chapter</span>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="m-portlet__body">
                <input type="hidden">

                <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                    <thead>
                    <tr>

                        <th> Sr NO.</th>
                        <th> Name</th>
                        <th> Dua</th>
                        <th> Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!empty($subCategories))
                        @foreach($subCategories as $subCategory)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{ucfirst($subCategory->title)}}</td>
                                    <td>{{$subCategory->category->title}}</td>
                                    <td nowrap style="width: 12%;">
                                        <a href="{{route('admin.dua-sub-categories.edit',$subCategory->id)}}"
                                           class="btn btn-sm btn-info pull-left ">Edit</a>
                                        <form method="post" action="{{ route('admin.dua-sub-categories.destroy', $subCategory->id) }}"
                                              id="delete_{{ $subCategory->id }}">
                                            @csrf
                                            @method('DELETE')
                                            <a style="margin-left:10px;" class="btn btn-sm btn-danger m-left"
                                               href="javascript:void(0)"
                                               onclick="if(confirmDelete()){ document.getElementById('delete_<?=$subCategory->id?>').submit(); }">
                                                Delete
                                            </a>
                                        </form>
                                    </td>
                                </tr>

                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        $("#m_table_1").dataTable({
            "ordering": false,
            "order": [[0, "desc"]],
            "columnDefs": [
                {orderable: false, targets: [3]}
            ],
        });

    </script>
@endpush